### ISSUE TITLE
New software request: Name: tmhmm_and_signalp version: 9

### ISSUE THREAD

**Issue by QFAB-Ops** [usegalaxy-au/usegalaxy-au-tools#628] opened 2021-10-20 08:12 UTC
# New software requested submitted - Galaxy Australia

<label for="typeInstall">What type of resource would you like installed?</label> tool

<label for="toolName">Name and version of software/tool to be installed/updated</label>: Name: tmhmm_and_signalp version: 9
<label for="toolAvail">Is the tool available from the Galaxy Toolshed?</label> yes

<label for="toolURL">URL to the tool in the Galaxy Toolshed repository</label>:  https://toolshed.g2.bx.psu.edu/view/anmoljh/trinitystats/8fd7b0c6ec0e

**Comment by cat-bro** [comment] 2021-12-22 02:10
duplicate of #631

**Closed by cat-bro** 2021-12-22 02:10 UTC
